SET(Chimera_VERSION 0.0.1)
SET(Chimera_MAJOR_VERSION 0)
SET(Chimera_MAJOR_MINOR_VERSION 000001)
SET(Chimera_VERSION_STRING "0.0.1 (Dev)")
SET(Chimera_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
