SET(MCLS_VERSION 0.0.1)
SET(MCLS_MAJOR_VERSION 0)
SET(MCLS_MAJOR_MINOR_VERSION 000001)
SET(MCLS_VERSION_STRING "0.0.1 (Dev)")
SET(MCLS_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
